### ISSUE TITLE
What is this repo (copy?) for? How does it work?

### ISSUE THREAD

**Issue by myfairsyer** [Microsoft/vscode-wiki#78]
Until now I assumed this wiki is the same as (and probably direct source of) vscode repo's wiki.
(I never worked with GitHub wikis)

Now I found out they apparently aren't and files and their histories even differ.

So what is this repo actually for and why do you keep two copies of the wiki?

Thanks a ton for answering!

**Comment by Tyriar** [comment]
I described how it works in a personal blog post https://www.growingwiththeweb.com/2016/07/enabling-pull-requests-on-github-wikis.html

Basically since github does not allow PRs to wikis, this is a clone of the vscode wiki and we have a nightly job that syncs the 2. I notice the job's been failing due to CI migration stuff, I'll follow this up :)
